### ISSUE TITLE
Implement GameObject-Component-Pattern

### ISSUE THREAD

**Issue by danielspaniol** [danielspaniol/8BitToHell#5]
## Use Context
As a _level designer_
I want _to be able to place game-objects in the game-world_
so that _the scene actually contains something the user can play with something_

## ToBe Solution
The basic concept is that there are **GameObject**s which can be placed in the world. GameObject can have children who themselves are GameObjects. GameObjects can have **Components** which define data and behavior for them. The toplevel GameObjects are placed at absolute positions in the world, children are always placed relative to their parents.

The syntax to create these objects shall follow the builder style used for the scenes.
   
    scene {
        world {
            gameObject {
                name { "Player" }
                tag { "Friendly" }
                transform {
                    x { 100 }
                    y { 200 }
                    rotation { 0 }
                }
                actorAnimator {
                    play { 
                        animation { Assets.PLAYER_IDLE_ANIMATION }
                        on { "PlayerIdle" } 
                    }
                    play {
                        animation { Assets.PLAYER_WALK_LEFT_ANIMATION }
                        on { "PlayerWalksLeft" } 
                    }
                    play {
                        animation { Assets.PLAYER_DIE_ANIMATION }
                        on { "PlayerDies" }
                        repeating { false } 
                    }
                }
                hitbox { /* ... */ }
                mass { 70.kg }
                gameObject {
                    name { "Weapon" }
                    // ....
                }
            }
        }
    }

## Tasks
- [x] Create `GameObject` class
    - It contains a set of children
    - ~~It contains a set of `Components`~~
    - It knows who its parent is
- [ ] ~~Create `Component` interface~~
    - ~~Maybe just a marker interface like `Serializable`?~~
- [x] Create `World` class
    - It contains a set of all `GameObject`s
    - Can add, remove and find `GameObject`s
- [x] Update `Scene` to use this model
    - The Scene has a `World`
    - Create a `WorldBuilder` (`SceneBuilder::world{}` should work)

**Comment by danielspaniol** [comment]
Removed tasks for `Component`... I will do it in a later issue
