### ISSUE TITLE
Create Prototyping

### ISSUE THREAD

**Issue by danielspaniol** [danielspaniol/8BitToHell#8]
## Use Context
As a _level designer_
I want _to create prototypes for GameObjects_
so that I don't have to copy-paste all the GameObjects_

## ToBe Solution
Prototypes will be simple GameObject that can be cloned into the GameWorld. <br>
This coping should be done without any major effort by the level designer. <br>
When I add a prototype into the game-world I still want to be able to change the attribute of the components.

## Tasks
- [ ] Make GameObjects `clonable`
- [x] Create a store for GameObject prototypes
- [x] Add a `FromPrototyp`-GameObjectBuilder to the Scene-Creation
