### ISSUE TITLE
Create Visuals-Loaders

### ISSUE THREAD

**Issue by danielspaniol** [danielspaniol/8BitToHell#9]
## Use Context
As a _player_
I want _to see stuff in the game-world_
so that _I understand what happens_

## Tasks
- [ ] enable deferred loading
- [ ] create `imageResource`-loader function
- [ ] create `spriteSheetResource`-loader function
- [ ] create `spriteResource`-loader function
- [ ] create `animationResource`-loader function
